# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Roughly Cooking
tagline:          Learning to cook by feel.
description:      'Helping redefine how we learn to cook using ratios, recipes and whole ingredients.'
url:              http://roughlycooking.com

author:
  name:           'Roughly Chef'
  url:            https://twitter.com/roughlycooking

paginate:         5