# Site settings
title: Roughly Cooking
email: amcglothlin@gmail.com
description: Learning to cook by feel and ratios. In the pursuit of simplicity in learning.
baseurl: "/roughly-cooking" # the subpath of your site, e.g. /blog/
url: "http://roughlycooking.com" # the base hostname & protocol for your site
twitter_username: roughlycooking
github_username:  roughlycooking

# Build settings
markdown: kramdown
